spring.application.name=ufc
server.address=0.0.0.0
server.port=8080

# DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/UFC_COMPILANCE?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=admin@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
# Disable schema validation to allow app start without Flyway
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway disabled
spring.flyway.enabled=false
# spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=JMhMBePz52OPKLqcsVDRQqe/o/wKXuSyU8UsbSiT032KwQ0JNNi1MB1Bb+SDMNOJPd04PnxPvJM0F7JM+jrm1g==
jwt.access.expiration=900000
jwt.refresh.expiration=604800000
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.show-sql=true

# Static resources
spring.web.resources.static-locations=file:D:/UFC/

# Mail configuration (required for JavaMailSender bean used by OTP API)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=evilmani0311@gmail.com
spring.mail.password=jhalbigiblzmovmt

# JMS / ActiveMQ Artemis (embedded – no external broker required)
spring.artemis.mode=embedded
spring.artemis.embedded.enabled=true
spring.artemis.embedded.queues=report.generation.queue
spring.jms.pub-sub-domain=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
